### ISSUE TITLE
I need a newer version of the browser. 

### ISSUE THREAD

**Issue by Boblet67** [ChristopherHX/linux-packaging-scripts#14]
I am ashamed to say this but, I have restrictions on my account (the one I bought minecraft bedrock on) and whenever I sign in I get this complaint: 
![2022-08-24-175911_1280x1024_scrot](https://user-images.githubusercontent.com/104725729/186482382-7c5db790-4673-4ac6-bd70-c72f782d45ba.png)

I don't know what needs updating, (so that's why the title is so vague). **_I know now. (according to yeenyeenyeen its the browser client)_**
This is probably going to be hard to solve but any attempts would be helpful. 
Thanks!

**Comment by opossm** [comment]
This is probably due to the browser client and user agent the launcher uses during the log in process. Family link may prevent certain browsers and devices from logging in. The current agent uses  Android 5.1, though Family Link requires 7.0.

**Comment by Boblet67** [comment]
Seems correct.

**Comment by Boblet67** [comment]
Ahhhh how did i post this here?
